// <auto-generated />
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskDeck.Core;
using TaskDeck.Core.Entities;
using TaskDeck.Data.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TaskDeck.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class TaskTemplateItemEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "TaskDeck.Core.Entities.TaskTemplateItem",
                typeof(TaskTemplateItem),
                baseEntityType,
                propertyCount: 18,
                foreignKeyCount: 2,
                unnamedIndexCount: 2,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var createdAt = runtimeEntityType.AddProperty(
                "CreatedAt",
                typeof(DateTime),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("CreatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<CreatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcDateTimeConverter());
            createdAt.SetSentinelFromProviderValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

            var deletedAt = runtimeEntityType.AddProperty(
                "DeletedAt",
                typeof(DateTime?),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("DeletedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<DeletedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new UtcDateTimeConverter());

            var depth = runtimeEntityType.AddProperty(
                "Depth",
                typeof(int),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("Depth", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<Depth>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var dueOffsetDays = runtimeEntityType.AddProperty(
                "DueOffsetDays",
                typeof(int?),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("DueOffsetDays", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<DueOffsetDays>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var dueTime = runtimeEntityType.AddProperty(
                "DueTime",
                typeof(TimeOnly?),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("DueTime", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<DueTime>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 5);
            dueTime.SetValueConverter(new ValueConverter<TimeOnly, string>(
                string (TimeOnly v) => v.ToString("HH:mm", CultureInfo.InvariantCulture),
                TimeOnly (string v) => TimeOnly.ParseExact(v, "HH:mm", CultureInfo.InvariantCulture, DateTimeStyles.None)));

            var durationMinutes = runtimeEntityType.AddProperty(
                "DurationMinutes",
                typeof(int?),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("DurationMinutes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<DurationMinutes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var notes = runtimeEntityType.AddProperty(
                "Notes",
                typeof(string),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("Notes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<Notes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var parentItemId = runtimeEntityType.AddProperty(
                "ParentItemId",
                typeof(Guid?),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("ParentItemId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<ParentItemId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var priority = runtimeEntityType.AddProperty(
                "Priority",
                typeof(Priority),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("Priority", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<Priority>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            priority.SetSentinelFromProviderValue(0);

            var remindOffsetMinutes = runtimeEntityType.AddProperty(
                "RemindOffsetMinutes",
                typeof(int?),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("RemindOffsetMinutes", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<RemindOffsetMinutes>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var remoteUpdatedAt = runtimeEntityType.AddProperty(
                "RemoteUpdatedAt",
                typeof(DateTime?),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("RemoteUpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<RemoteUpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                valueConverter: new UtcDateTimeConverter());

            var sortOrder = runtimeEntityType.AddProperty(
                "SortOrder",
                typeof(double),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("SortOrder", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<SortOrder>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var syncState = runtimeEntityType.AddProperty(
                "SyncState",
                typeof(SyncState),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("SyncState", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<SyncState>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            syncState.SetSentinelFromProviderValue(0);

            var tagIds = runtimeEntityType.AddProperty(
                "TagIds",
                typeof(List<Guid>),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("TagIds", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<TagIds>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            tagIds.SetValueConverter(new ValueConverter<List<Guid>, string>(
                string (List<Guid> v) => string.Join(',', v.Select(string (Guid g) => g.ToString("D"))),
                List<Guid> (string v) => GuidListConverter.Parse(v)));
            tagIds.SetComparer(new ValueComparer<List<Guid>>(
                bool (List<Guid> a, List<Guid> b) => (a != null && b != null ? a.SequenceEqual(b) : a == b),
                int (List<Guid> v) => v.Aggregate(0, int (int h, Guid g) => HashCode.Combine(h, ((object)g).GetHashCode())),
                List<Guid> (List<Guid> v) => v.ToList()));

            var templateId = runtimeEntityType.AddProperty(
                "TemplateId",
                typeof(Guid),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("TemplateId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<TemplateId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));

            var title = runtimeEntityType.AddProperty(
                "Title",
                typeof(string),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("Title", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<Title>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                maxLength: 500);

            var updatedAt = runtimeEntityType.AddProperty(
                "UpdatedAt",
                typeof(DateTime),
                propertyInfo: typeof(TaskTemplateItem).GetProperty("UpdatedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(TaskTemplateItem).GetField("<UpdatedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcDateTimeConverter());
            updatedAt.SetSentinelFromProviderValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { parentItemId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { templateId, sortOrder });
            index0.AddAnnotation("Relational:Name", "IX_TemplateItem_Tpl");

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ParentItemId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.SetNull);

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("TemplateId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Cascade,
                required: true);

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "TaskTemplateItem");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
