// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using TaskDeck.Data;
using TaskDeck.Data.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(TaskDeckDbContext), typeof(TaskDeckDbContextModel))]
