// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TaskDeck.Data.CompiledModels
{
    public partial class TaskDeckDbContextModel
    {
        private TaskDeckDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("0a4d451d-889a-4f59-bc72-98f4c1660e94"), entityTypeCount: 12)
        {
        }

        partial void Initialize()
        {
            var appStateEntry = AppStateEntryEntityType.Create(this);
            var holiday = HolidayEntityType.Create(this);
            var linkPreview = LinkPreviewEntityType.Create(this);
            var project = ProjectEntityType.Create(this);
            var recurrenceRule = RecurrenceRuleEntityType.Create(this);
            var syncMeta = SyncMetaEntityType.Create(this);
            var tag = TagEntityType.Create(this);
            var taskItem = TaskItemEntityType.Create(this);
            var taskTag = TaskTagEntityType.Create(this);
            var taskTemplate = TaskTemplateEntityType.Create(this);
            var taskTemplateItem = TaskTemplateItemEntityType.Create(this);
            var weatherDay = WeatherDayEntityType.Create(this);

            TaskItemEntityType.CreateForeignKey1(taskItem, taskItem);
            TaskItemEntityType.CreateForeignKey2(taskItem, project);
            TaskItemEntityType.CreateForeignKey3(taskItem, recurrenceRule);
            TaskTagEntityType.CreateForeignKey1(taskTag, tag);
            TaskTagEntityType.CreateForeignKey2(taskTag, taskItem);
            TaskTemplateEntityType.CreateForeignKey1(taskTemplate, project);
            TaskTemplateItemEntityType.CreateForeignKey1(taskTemplateItem, taskTemplateItem);
            TaskTemplateItemEntityType.CreateForeignKey2(taskTemplateItem, taskTemplate);

            AppStateEntryEntityType.CreateAnnotations(appStateEntry);
            HolidayEntityType.CreateAnnotations(holiday);
            LinkPreviewEntityType.CreateAnnotations(linkPreview);
            ProjectEntityType.CreateAnnotations(project);
            RecurrenceRuleEntityType.CreateAnnotations(recurrenceRule);
            SyncMetaEntityType.CreateAnnotations(syncMeta);
            TagEntityType.CreateAnnotations(tag);
            TaskItemEntityType.CreateAnnotations(taskItem);
            TaskTagEntityType.CreateAnnotations(taskTag);
            TaskTemplateEntityType.CreateAnnotations(taskTemplate);
            TaskTemplateItemEntityType.CreateAnnotations(taskTemplateItem);
            WeatherDayEntityType.CreateAnnotations(weatherDay);

            AddAnnotation("ProductVersion", "10.0.12");
        }
    }
}
