// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using TaskDeck.Core.Entities;
using TaskDeck.Data.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

namespace TaskDeck.Data.CompiledModels
{
    [EntityFrameworkInternal]
    public partial class WeatherDayEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "TaskDeck.Core.Entities.WeatherDay",
                typeof(WeatherDay),
                baseEntityType,
                propertyCount: 6,
                keyCount: 1);

            var date = runtimeEntityType.AddProperty(
                "Date",
                typeof(DateOnly),
                propertyInfo: typeof(WeatherDay).GetProperty("Date", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WeatherDay).GetField("<Date>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new DateOnly(1, 1, 1));

            var fetchedAt = runtimeEntityType.AddProperty(
                "FetchedAt",
                typeof(DateTime),
                propertyInfo: typeof(WeatherDay).GetProperty("FetchedAt", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WeatherDay).GetField("<FetchedAt>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueConverter: new UtcDateTimeConverter());
            fetchedAt.SetSentinelFromProviderValue(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc));

            var precipitationProbability = runtimeEntityType.AddProperty(
                "PrecipitationProbability",
                typeof(int?),
                propertyInfo: typeof(WeatherDay).GetProperty("PrecipitationProbability", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WeatherDay).GetField("<PrecipitationProbability>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);

            var temperatureMax = runtimeEntityType.AddProperty(
                "TemperatureMax",
                typeof(double),
                propertyInfo: typeof(WeatherDay).GetProperty("TemperatureMax", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WeatherDay).GetField("<TemperatureMax>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var temperatureMin = runtimeEntityType.AddProperty(
                "TemperatureMin",
                typeof(double),
                propertyInfo: typeof(WeatherDay).GetProperty("TemperatureMin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WeatherDay).GetField("<TemperatureMin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0.0);

            var weatherCode = runtimeEntityType.AddProperty(
                "WeatherCode",
                typeof(int),
                propertyInfo: typeof(WeatherDay).GetProperty("WeatherCode", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(WeatherDay).GetField("<WeatherCode>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);

            var key = runtimeEntityType.AddKey(
                new[] { date });
            runtimeEntityType.SetPrimaryKey(key);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "WeatherCache");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
