// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskDeck.Data;

#nullable disable

namespace TaskDeck.Data.Migrations
{
    [DbContext(typeof(TaskDeckDbContext))]
    [Migration("20260922162924_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TaskDeck.Core.Entities.AppStateEntry", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppState", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.Holiday", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Date");

                    b.ToTable("Holiday", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.LinkPreview", b =>
                {
                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Url");

                    b.ToTable("LinkPreview", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemoteUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt", "SortOrder")
                        .HasDatabaseName("IX_Project_Order");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.RecurrenceRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnchorAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RRule")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemoteUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RecurrenceRule", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.SyncMeta", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncCursor")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncMeta", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime?>("RemoteUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Tag_Name")
                        .HasFilter("\"DeletedAt\" IS NULL");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DueHasTime")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NotifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecurrenceRuleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RecurrenceSeriesId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemindAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RemindOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RemoteUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<double>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TemplateBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId")
                        .HasDatabaseName("IX_Task_Parent");

                    b.HasIndex("RecurrenceRuleId");

                    b.HasIndex("RecurrenceSeriesId")
                        .HasDatabaseName("IX_Task_Series");

                    b.HasIndex("RemindAt")
                        .HasDatabaseName("IX_Task_Remind")
                        .HasFilter("\"NotifiedAt\" IS NULL AND \"DeletedAt\" IS NULL");

                    b.HasIndex("SyncState")
                        .HasDatabaseName("IX_Task_Sync");

                    b.HasIndex("TemplateBatchId")
                        .HasDatabaseName("IX_Task_Batch");

                    b.HasIndex("ProjectId", "DeletedAt")
                        .HasDatabaseName("IX_Task_Project");

                    b.HasIndex("Status", "CompletedAt")
                        .HasDatabaseName("IX_Task_Completed");

                    b.HasIndex("DeletedAt", "Status", "DueAt")
                        .HasDatabaseName("IX_Task_Due");

                    b.ToTable("TaskItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_TaskItem_Depth", "\"Depth\" >= 0 AND \"Depth\" <= 2");
                        });
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.TaskTag", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("TaskId", "TagId");

                    b.HasIndex("TagId", "DeletedAt")
                        .HasDatabaseName("IX_TaskTag_Tag");

                    b.ToTable("TaskTag", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.TaskTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnchorLabel")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultTagIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconKey")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemoteUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UseCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DefaultProjectId");

                    b.HasIndex("DeletedAt", "UseCount")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Template_Use");

                    b.ToTable("TaskTemplate", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.TaskTemplateItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DueOffsetDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueTime")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RemindOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RemoteUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("SortOrder")
                        .HasColumnType("REAL");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentItemId");

                    b.HasIndex("TemplateId", "SortOrder")
                        .HasDatabaseName("IX_TemplateItem_Tpl");

                    b.ToTable("TaskTemplateItem", null, t =>
                        {
                            t.HasCheckConstraint("CK_TaskTemplateItem_Depth", "\"Depth\" >= 0 AND \"Depth\" <= 2");
                        });
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.WeatherDay", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrecipitationProbability")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TemperatureMax")
                        .HasColumnType("REAL");

                    b.Property<double>("TemperatureMin")
                        .HasColumnType("REAL");

                    b.Property<int>("WeatherCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Date");

                    b.ToTable("WeatherCache", (string)null);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskDeck.Core.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskDeck.Core.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskDeck.Core.Entities.RecurrenceRule", null)
                        .WithMany()
                        .HasForeignKey("RecurrenceRuleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.TaskTag", b =>
                {
                    b.HasOne("TaskDeck.Core.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskDeck.Core.Entities.TaskItem", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.TaskTemplate", b =>
                {
                    b.HasOne("TaskDeck.Core.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("DefaultProjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TaskDeck.Core.Entities.TaskTemplateItem", b =>
                {
                    b.HasOne("TaskDeck.Core.Entities.TaskTemplateItem", null)
                        .WithMany()
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TaskDeck.Core.Entities.TaskTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
